version: '3'
services: 
  database:
    container_name: ticket-db
    image: postgres
    volumes: 
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: ticket-db
      POSTGRES_USER: gdgadmin
      POSTGRES_PASSWORD: corona2020
  api:
    container_name: ticket-api
    build: .
    depends_on: 
      - database
    ports: 
      - "8080:3000"
    restart: always
volumes:
  db_data: {}